name: "GKE Allow Runner Action"
description: "Add or remove the current GitHub runner IP from GKE master authorized networks"
author: "sysdown"
repository: "https://github.com/1xor3us/gke-allow-runner-action"

branding:
  icon: "lock"
  color: "blue"

inputs:
  clusters:
    description: |
      Liste des clusters GKE à mettre à jour (format: region/cluster-name).
      Exemple multi-ligne :
        europe-west1/cluster-test
        us-central1/cluster-prod
    required: true

  project_id:
    description: "ID du projet GCP"
    required: true

  action:
    description: "Action à effectuer : 'allow' pour ajouter, 'cleanup' pour supprimer."
    required: false
    default: "allow"

  credentials_json:
    description: "Clé JSON du service account GCP (via secret)"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  env:
    INPUT_CLUSTERS: ${{ inputs.clusters }}
    INPUT_PROJECT_ID: ${{ inputs.project_id }}
    INPUT_ACTION: ${{ inputs.action }}
    INPUT_CREDENTIALS_JSON: ${{ inputs.credentials_json }}